Automatically identify build failure causes (#174)
This allows us to continously monitor a given day for error causes.

When a new issue is created for a broken snapshot build, we'll check the
logs of the failing builds for anything that we identify as an error.
The errors we can identify so far are listed below. A github issue label (i.e. `error/copr_timeout`, `error/network_issue`) is then automatically added to the broken snapshot issue.

# Examples of error causes

## `copr_timeout`

<pre>
 <b>!! Copr timeout</b> => sending INT
WARNING: Machine 5851d3319caf45608112626e5dff90dc still running. Killing...
Copr build error: Build failed
</pre>

## `network_issue`

<pre>
<b>Errors during downloading metadata for repository</b> 'local':
  - Status code: 404 for https://kojipkgs.fedoraproject.org/repos/rawhide/latest/x86_64/repodata/c3262644a11234a683575d44416933749f6808ea60694a499b11336c3b735223-filelists.xml.gz (IP: 38.145.60.20)
  - Status code: 404 for https://kojipkgs.fedoraproject.org/repos/rawhide/latest/x86_64/repodata/729723bef89105229ca2204cb1fdb395e04630c92e8119a2a3eec1c70dcb1a62-primary.xml.gz (IP: 38.145.60.20)
Error: Failed to download metadata for repo 'local': Yum repo downloading error: Downloading error(s): repodata/729723bef89105229ca2204cb1fdb395e04630c92e8119a2a3eec1c70dcb1a62-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/c3262644a11234a683575d44416933749f6808ea60694a499b11336c3b735223-filelists.xml.gz - Cannot download, all mirrors were already tried without success
</pre>

## `test_issue`

<pre>
PASS: lit :: shtest-define.py (73079 of 73079)
********************
<b>Failed Tests</b> (1):
  libarcher :: races/task-taskgroup-unrelated.c


Testing Time: 226.85s

<b>Total Discovered Tests:</b> 96435
  Skipped          :    50 (0.05%)
  Unsupported      :  2416 (2.51%)
  Passed           : 93787 (97.25%)
  Expectedly Failed:   181 (0.19%)
  Failed           :     1 (0.00%)
</pre>

## `dependency_issue`

<pre>
No matching package to install: 'llvm-googletest = 18.0.0~pre20240108.g60c4f82d3c4e9c'
No matching package to install: 'llvm-static = 18.0.0~pre20240108.g60c4f82d3c4e9c'
No matching package to install: 'llvm-test = 18.0.0~pre20240108.g60c4f82d3c4e9c'
<b>Not all dependencies satisfied</b>
Error: Some packages could not be found.
WARNING: DNF command failed, retrying, attempt #2, sleeping 10s
No matches found for the following disable plugin patterns: local, spacewalk, versionlock
</pre>

## `unknown`

Anything that we cannot identify as one of the above error causes will be classified as `unknown`. Those are probably the most interesting errors to look into. That is why this change materializes the tail of the build log as a comment on the issue related to a broken snapshot.