Use python venv to run tests, coverage and building diagrams locally (#1132)
This change adds these make targets:

* `venv` to create a virtual environment in `.venv` to be used by make targets below
  * NOTE: The `dnf` module needs to be installed through the operating system but we make it available to the venv by passing `--system-site-packages`.
* `test` runs tests in the virtual environment created above
* `coverage` runs coverage and produces a text and HTML report in the virtual environment created above
* `update-requirements` this is a helper target to update `requirements.txt` when you change something in `requirements.txt.in`. This is also done in the venv created above.

Other changes:

* `requirements.txt` got `pytest` as a new dependency because we use it in some tests.
* `.coveragerc` was added to include configuration for which files to omit from coverage.
  * Without this, coverage would include `/usr` directories.
* `*_test.py` files will now be excluded from the coverage because we're not interested in them.

* `cffi` was bumped from `1.15.1` to `1.17.1` for it to work with Python 3.13

This should fix this error:

```
      building '_cffi_backend' extension
      creating build/temp.linux-x86_64-cpython-313/c
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -O3 -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/home/kkleine/src/llvm-snapshots/.venv/include -I/usr/include/python3.13 -c c/_cffi_backend.c -o build/temp.linux-x86_64-cpython-313/c/_cffi_backend.o
      c/_cffi_backend.c: In function ‘b_do_dlopen’:
      c/_cffi_backend.c:4523:22: warning: ‘Py_FileSystemDefaultEncoding’ is deprecated [-Wdeprecated-declarations]
       4523 |                      Py_FileSystemDefaultEncoding, &filename_or_null, &flags))
            |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /usr/include/python3.13/Python.h:99,
                       from c/_cffi_backend.c:2:
      /usr/include/python3.13/fileobject.h:22:46: note: declared here
         22 | Py_DEPRECATED(3.12) PyAPI_DATA(const char *) Py_FileSystemDefaultEncoding;
            |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      c/_cffi_backend.c: In function ‘_my_PyErr_WriteUnraisable’:
      c/_cffi_backend.c:6112:9: error: implicit declaration of function ‘_PyErr_WriteUnraisableMsg’; did you mean ‘PyErr_WriteUnraisable’? [-Wimplicit-function-declaration]
       6112 |         _PyErr_WriteUnraisableMsg(PyText_AS_UTF8(s), NULL);
            |         ^~~~~~~~~~~~~~~~~~~~~~~~~
            |         PyErr_WriteUnraisable
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cffi
Failed to build cffi
```