Build and upload man pages alongside other snapshot version information
DO NOT MERGE BEFORE THIS WAS MERGED: https://src.fedoraproject.org/rpms/llvm/pull-request/607

* Don't waste time searching for a good commit. Just run one check and
  then take main.

* I also ran `precommit autoupdate` because without that I ran into this
error which to me looks like an error not on my side.

    pyupgrade................................................................Failed
    - hook id: pyupgrade
    - exit code: 1

    Traceback (most recent call last):
      File "/home/kkleine/.cache/pre-commit/repo68ioyw5f/py_env-python3.14/bin/pyupgrade", line 8, in <module>
        sys.exit(main())
                 ~~~~^^
      File "/home/kkleine/.cache/pre-commit/repo68ioyw5f/py_env-python3.14/lib/python3.14/site-packages/pyupgrade/_main.py", line 389, in main
        ret |= _fix_file(filename, args)
               ~~~~~~~~~^^^^^^^^^^^^^^^^
      File "/home/kkleine/.cache/pre-commit/repo68ioyw5f/py_env-python3.14/lib/python3.14/site-packages/pyupgrade/_main.py", line 327, in _fix_file
        contents_text = _fix_tokens(contents_text)
      File "/home/kkleine/.cache/pre-commit/repo68ioyw5f/py_env-python3.14/lib/python3.14/site-packages/pyupgrade/_main.py", line 297, in _fix_tokens
        tokenize.cookie_re.match(token.src)
        ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
    TypeError: cannot use a bytes pattern on a string-like object

* Fixes a deprecation warning while at it:

    DeprecationWarning: Argument login_or_token is deprecated, please use
    auth=github.Auth.Token(...) instead