Added missing required property:
Should fix this github error:

```
 Error: /home/runner/work/llvm-snapshots/llvm-snapshots/./.github/actions/prepare-python/action.yml (Line: 26, Col: 7): Required property is missing: shell
```

Fixup for #230