Fix for missing rpm.open in rpm < 4.17.0
Fixes this error:

```
error: lua script failed: [string "<lua>"]:57: attempt to call a nil value (field 'open')
```