Automatically identify build failure causes
This allows us to continously monitor a given day for error causes.

When a new issue is created for a broken snapshot build, we'll check the
logs of the failing builds for anything that we identify as an error.
The errors we can identify so far are copr timeouts (`copr_timeout`):

```
 !! Copr timeout => sending INT
WARNING: Machine 5851d3319caf45608112626e5dff90dc still running. Killing...
Copr build error: Build failed
```

and network issues (`network_issue`):

```
Errors during downloading metadata for repository 'local':
  - Status code: 404 for https://kojipkgs.fedoraproject.org/repos/rawhide/latest/x86_64/repodata/c3262644a11234a683575d44416933749f6808ea60694a499b11336c3b735223-filelists.xml.gz (IP: 38.145.60.20)
  - Status code: 404 for https://kojipkgs.fedoraproject.org/repos/rawhide/latest/x86_64/repodata/729723bef89105229ca2204cb1fdb395e04630c92e8119a2a3eec1c70dcb1a62-primary.xml.gz (IP: 38.145.60.20)
Error: Failed to download metadata for repo 'local': Yum repo downloading error: Downloading error(s): repodata/729723bef89105229ca2204cb1fdb395e04630c92e8119a2a3eec1c70dcb1a62-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/c3262644a11234a683575d44416933749f6808ea60694a499b11336c3b735223-filelists.xml.gz - Cannot download, all mirrors were already tried without success
```

A label of `error/copr_timeout` or `error/network_issue` is then
automatically added to the broken snapshot issue.