Fix for missing rpm.execute in rpm < 4.15.0
Fixes this error:

```
error: lua script failed: [string "<lua>"]:50: attempt to call a nil value (field 'execute')
```