llvm-snapshot-builder: Fix yyyymmdd definition
I don't think defines are allowed in the system macro files, so this was
causing an error:

error: /usr/lib/rpm/macros.d/macros.llvm-snapshot-builder: line 209: Macro % has illegal name (%define)